### PR TITLE
Adding the RunTIme Testers

### PR DESCRIPTION
**Pull request by MAGNUSGAO**
Hello Gabriel,

     I added the runTimeTesters to the repo.

### CODE REVIEW

**Comment by Gadiguibou** [comment]
Looks good to me. It looks like you've got some merge conflicts. Do you know if you could resolve these before we merge? I'm not sure if it's just that you're a few commits behind the main branch or if you've actually added things to `Tester.java`.

~~On a side note, I'm going to work on the last few functions that we've got to test for time complexity.~~

Edit: Just realized generateNextKeystreamValue() already includes the time complexity of all the other methods if they're O(N).

**Comment by MAGNUSGAO** [comment]
Thank you Gabriel, I will update my tester.java to the newest version and send another pull request!

**Comment by MAGNUSGAO** [comment]
Hello Gabriel,

     I am not sure what happened to Tester.java. I literally copy pasted
from your repo but it still says it's different. I will attach the file
below. Would you mind manually "adding" it to the src /asgn2 folder? Thank
you.

Magnus

**Comment by Gadiguibou** [comment]
That's strange, I'll merge @louis-hildebrand's PR. I hope that fixes it.

**Pull request closed without merging**
