### PR TITLE
Add test for moveCard() with large p

### PR DESCRIPTION
**Pull request by louis-hildebrand**
I took a quick look through Piazza and found another spicy edge case (question 1209).

Edit: while fixing my own code to pass this test I found that some of the other tests got stuck in infinite loops for some reason. I replaced all the while loops by calls to Tester.deckToString() and it seems to work better now. While I was at it, I also removed some sections of code that didn't seem to do anything (I hope @ysarasty doesn't mind).

### CODE REVIEW

**Comment by Gadiguibou** [comment]
That's a finicky one indeed!

**Comment by ysarasty** [comment]
No worries, the idea is to have a good tester :) -- on the other hand, the initial idea of the "while" was to track the numero of card on the deck and its consistency with the circular list, so, if there is a discrepancy between the card on your deck, the pointer to the head and numOfCards, the code will go to an infinity loop

**Comment by louis-hildebrand** [comment]
> ... the initial idea of the "while" was to track the numero of card on the deck and its consistency with the circular list, so, if there is a discrepancy between the card on your deck, the pointer to the head and numOfCards, the code will go to an infinity loop

It's good to check that the number of cards is consistent with the structure of the deck! It's just not helpful at all to send the tester into an infinite loop; that doesn't give the user any information and blocks them from seeing the list of tests they failed. Tester.deckToString() implicitly checks that the number of cards is correct, and if you want to explicitly check the references in the deck there's also Tester.checkReferences().

**Comment by ysarasty** [comment]
got it

**Pull request merged**
